FROM jsurf/rpi-raspbian:latest
MAINTAINER Alexander Adhyatma <alexadhyatma@mail.ru>

ENV WKHTMLTOX_ARMHF https://github.com/wkhtmltopdf/wkhtmltopdf/files/720814/wkhtmltopdf.zip

# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
RUN set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            node-less \
            node-clean-css \
            python-pyinotify \
            wkhtmltopdf \
	    unzip \
            python-renderpm
            # not anymore on ubuntu 16.04
            # python-support
RUN set -x; \
        curl -o wkhtmltox.zip -SL ${WKHTMLTOX_ARMHF} \
	&& unzip wkhtmltox.zip \
        && mv wkhtmltopdf /usr/bin/wkhtmltopdf \
        && apt-get -y install -f --no-install-recommends \
        && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false npm \
        && rm -rf /var/lib/apt/lists/* wkhtmltox.zip

# Install Odoo
ENV ODOO_VERSION 8.0
ENV ODOO_RELEASE 20170213
RUN set -x; \
        curl -o odoo.deb -SL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb \
        && dpkg --force-depends -i odoo.deb \
        && apt-get update \
        && apt-get -y install -f --no-install-recommends \
        && rm -rf /var/lib/apt/lists/* odoo.deb

# Copy entrypoint script and Odoo configuration file
COPY ./entrypoint.sh /
COPY ./openerp-server.conf /etc/odoo/
RUN chown odoo /etc/odoo/openerp-server.conf

# Mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
RUN mkdir -p /mnt/extra-addons \
        && chown -R odoo /mnt/extra-addons
VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]

# Expose Odoo services
EXPOSE 8069 8071

# Set the default config file
ENV OPENERP_SERVER /etc/odoo/openerp-server.conf

# Set default user when running the container
USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["openerp-server"]
